# Site settings
url: "http://angstrom.io" # the base hostname & protocol for your site
title: life and code &middot; in small doses
author: Christopher Coco
email:
description:
baseurl: "" # the subpath of your site, e.g. /blog/

date_format: "%A, %B %-d %Y"

exclude: [ README.md, Gemfile, Gemfile.lock ]
timezone: America/Los_Angeles
encoding: utf-8

# Build settings
markdown: rdiscount
rdiscount:
  extensions: [ footnotes ]

# If publishing to a subdirectory as in http://site.com/project set 'root: /project'
permalink: /blog/:year/:month/:day/:title/
category_dir: blog/categories
highlighter: pygments # default python pygments have been replaced by pygments.rb

paginate: 4                       # Posts per page on the blog index
pagination_dir: blog              # Directory base for pagination URLs eg. /blog/page/2/
recent_posts: 3                   # Posts in the sidebar Recent Posts section
excerpt_link: "Read on &rarr;"    # "Continue reading" link text at the bottom of excerpted articles
excerpt_separator: "<!-- more -->"

titlecase: true       # Converts page and post titles to titlecase

# list each of the sidebar modules you want to include, in the order you want them to appear.
# To add custom asides, create files in /source/_includes/custom/asides/ and add them to the list like 'custom/asides/custom_aside_name.html'
default_asides: [asides/recent_posts.html]
